apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: goapp-db
spec:
  interval: 1m0s
  timeout: 10m
  chart:
    spec:
      chart: postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
      version: "12.1.4"
  valuesFrom:
    - kind: Secret
      name: postgres-db-secret
      valuesKey: values.yaml