apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nginx-lb
spec:
  interval: 1m0s
  timeout: 10m
  chart:
    spec:
      chart: nginx-ingress-controller
      version: "11.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami-repo
  values:
    controller:
      replicaCount: 1
      service:
        type: LoadBalancer
      ingressClassResource:
        name: nginx