apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
type: Opaque
stringData:
    adminUser: ENC[AES256_GCM,data:Ta+1UX4=,iv:/0tMXeckKoGloSudCkJ6bSDT1ezCKwRmUNAwn7Mse2Y=,tag:6A6yyiscTMakL744JwYAIg==,type:str]
    adminPassword: ENC[AES256_GCM,data:iW9+M2gkyqQ=,iv:EwuoTma2GLosXc50HvNHauqL6KNCO7sE+nN99O9JBcc=,tag:143x3th4JAShHKPZUx2kzA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1tj9pk5vvg007rddv43ct4k9e75k5jzad90c0efvnmujk36yradas9akf33
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VTNoTXVqOXBLRVorOTdZ
            bm9lVEx0UzNVNWZ4clBpdmpISHNkTlVhNFhvCmZhNnRCSVAyZ3FNckIyMEVqTzFR
            cm83Q2Vxb3lLUGdudENiN1V4RDBsS2MKLS0tIGdCbzB6VzQ3TkNYczhYY25xM2pZ
            d2VJRXFESFlUeWpqb3RPWWZUZDFqSFkKCwwISwvdgHZb5v1GzxwLErrNk9eSLiCq
            BA2lfxgcAlxlUz8d/k5oKDjR5pJ0JikFPQTAYjesiwmeIRbvoosqQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-18T15:54:19Z"
    mac: ENC[AES256_GCM,data:COS9e5TKktksL8y7t/F9BOU1JjCZX4XD4Xm0Pv8aTUJNXaMisndrt985xFhKqrLzCPXRCCX5UpQLJLx6X6zSGoMdVXm7ki4SGsoJv3EQI1hnJ9hKxAMqXX/nrvXALyErvrKTj1C4m9fSr83w1AgGmWCMmT2vp+0FI2kwTrjBJn8=,iv:nGDma8LVgZC+BIOEuti8IuVwHKsoCpMrFLfAeDQngMU=,tag:gXek03NPUcC8FyRTZtj/Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
