apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tools

resources:
  - namespace.yaml
  - grafana
  - prometheus
  - loki
  - promtail
  - ../../../infrastructure/grafana-repo.yaml
  - ../../../infrastructure/prometheus-repo.yaml