# prometheus-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
spec:
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: prometheus
      version: 15.0.0     # Specify a stable version
      sourceRef:
        kind: HelmRepository
        name: prometheus-repo
  values:
    alertmanager:
      enabled: true
    pushgateway:
      enabled: false
    server:
      global:
        scrape_interval: 15s
      service:
        type: ClusterIP
