# promtail-helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: promtail
spec:
  interval: 1m
  timeout: 10m
  chart:
    spec:
      chart: promtail
      version: 3.1.0       # Specify a stable version
      sourceRef:
        kind: HelmRepository
        name: grafana-repo
  values:
    config:
      lokiAddress: "http://loki.tools:3100/loki/api/v1/push"
