all:
  hosts:
    jenkins-server:
      ansible_host: "{{ jenkins_master_ip }}"
      ansible_user: "{{ ansible_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"
    jenkins-agent-1:
      ansible_host: "{{ jenkins_agent_ip }}"
      ansible_user: "{{ ansible_user }}"
      ansible_ssh_private_key_file: "{{ ssh_key_path }}"