apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - secret.yaml
  - config.yaml
  - ingress.yaml
  - ../modules/docker-registry.yaml